image: cirrusci/flutter:3.0.1

stages:
  - build

build:
  stage: build
  script:
    - flutter doctor
    - flutter pub get
    - flutter analyze
    - cd example
    - flutter build apk
  only:
    - master
    - tags
    - merge_requests
